<!DOCTYPE html>
<html>
<head>
	<title>Privacy - AnchorID</title>
	<?php include('includes/head.php'); ?>
</head>
<body>
<!-- Header Starts Here -->
<?php include "includes/header.php";?>
<!-- About Page Starts Here -->
<div class="outer-container">
<div class="container">
	<div class="row about-row-setting">  

		<div class="col-md-12">
			
			<div id="section-content">
				<h1 class="main-heading">Privacy</h1>
				<h3>INTRODUCTION</h3>
				<p>Anchor ID, Inc. is focused on maintaining your privacy. With respect to your personal data, Anchor ID provides an important service to our customers to help, which makes it easier to use the web and mobile apps without the need to share personal data, and we start with this privacy policy. In short, we simply don't collect personal data about our customers, making it impossible for us to share it. That's right &ndash; we don't know, and don't ask you to tell us, your name, your address, your home or work phone number, your age, your gender, etc. We don't even require your email address if your don't want to share it.</p>
				<p>To operate our service, however, we only need the following three items:</p>
				<p>Mobile Phone Number: We ask for your mobile phone number, but only to verify that you can receive an activation code via text message, and to verify that you know the correct billing zip code for this account. Otherwise, we will never, ever, sell or share your mobile phone number with anyone.</p>
				<p>Voice Sample: We ask for your voice sample during registrations to ensure that you have a backup to your PIN. If you forget your PIN, your voice sample becomes our only way to recover your account. You also have the option of using this voice sample to log in to your accounts. Otherwise, we will never, ever, sell or share your Voice Sample with anyone.</p>
				<p>Zip Code: We ask for your zip code, and we may verify that you have entered the correct zip code with your mobile network operator. We may aggregate information about you with others in your zip code, and share with third parties.</p>
				<p>We want you to use Anchor ID to access many web sites and mobile apps. But, we also want you to trust us, which is why we will never ask for this personal data.</p>
				<p>Use of all information collected is detailed </p>

				<h3>APPLICABILITY OF THIS PRIVACY POLICY</h3>
				<p>This Privacy Policy describes Anchor ID, Inc.'s (&quot;Anchor ID&quot; or &quot;we&quot;) practices for gathering, storing, using and sharing information collected or otherwise obtained by Anchor ID both (i) via this website (the &quot;Website&quot;) and (ii) through your download (via a mobile device, tablet or other computer) of Anchor ID software or mobile apps (collectively, &quot;Applicable Software&quot;) and/or use of Anchor ID services facilitated by such Applicable Software (the &quot;Services&quot;), regardless of whether the Applicable Software or Services are branded as &quot;Anchor ID&quot; or as any Applicable Third Party (defined below). This Privacy Policy does not apply to any information that may be collected by Anchor ID through any other means, including offline. By visiting the Website or downloading and/or using the Applicable Software or the Services you are providing your explicit permission to Anchor ID to collect, store, use and share information as set forth in this Privacy Policy. If you do not agree with the terms and conditions set forth in this Privacy Policy, please do not use, download or access the Website or any Applicable Software, or the Services. Notwithstanding anything to the contrary herein, this Privacy Policy does not apply to information about you collected (i) by third party services, applications or websites, or advertisements associated with, linked to or otherwise accessible from the Website (including by a third party payment processor) or (ii) by third party individuals, retailers, financial institutions or other firms or companies, including your employer or client (collectively, &quot;Applicable Third Parties&quot;), with which you conduct transactions or communications facilitated and/or confirmed through use of the Services (&quot;Third Party Transactions&quot;).The information collected or received by such third parties is subject to their own privacy policies and under no circumstances is Anchor ID responsible or liable for the third party's compliance therewith.</p>

				<h3>HOW WE COLLECT INFORMATION</h3>
				<p>You can visit the Website anonymously without telling us who you are and without giving or having us collect any personal information about yourself. We collect limited personally identifiable information (i) when you register to become a user of the Services through the Website or in connection with the download the Applicable Software, (ii) when you sign up for an Anchor ID online service demonstration, (iii) when you &quot;opt in&quot; for certain services or features of the Website, such as electing to receive emails, (iv) when you voluntarily provide us with information through emails, and (iv) automatically as further described below. We receive the automatic and passive data (both personally identifiable and otherwise) from the computer, mobile phone or other device you use to download the Applicable Software or access and use the Website or the Services. In this regard, the Website uses common automated information gathering tools such as log files and &quot;cookies&quot; that identify users and record page activity, including a particular user's visits to a page and how many &quot;hits&quot; a particular item is receiving, as well as other user activity and interactions with the Website. Third party advertisements or functionality, which may be included on the Website, may also contain cookies sent by Internet advertising companies, advertisers or others (known as &quot;third party cookies&quot;). Most web browsers automatically accept cookies, but it is possible to change your browser setup so that it warns you each time a cookie is being sent, blocks third party cookies or blocks or rejects all cookies. However, rejecting cookies may prevent you from taking advantage of certain portions of the Website.</p>

				<h3>WHAT INFORMATION WE COLLECT</h3>
				<p>Via the Website. Via the Website, Anchor ID collects from you: (i) certain non-personal technical and other information and (ii) certain personally identifiable information. Non-Registered Users of the Website &ndash; In general, if you use the Website without registering with Anchor ID, you will be using the Website anonymously; no personally identifiable information is collected. However, we will collect certain non-personally identifiable information from non-registered users, as noted in &quot;All Users&quot; paragraph below. Registered Users of the Website &ndash; When you register with the Website, including registering for a demonstration, you will be asked to provide us with certain personally identifiable information, which may include a nickname (we do not require your legal name), zip code, voice sample and mobile phone numbers; email address; other contact information; and your 'Anchor ID Universal User Name'. Providing some of the requested information may be optional and Anchor ID will indicate what information is required and what is optional.</p>
				<p>All Users &ndash; Regardless of whether you are a registered or non-registered user, when you use the Website various types of information are collected automatically and passively through log files, cookies and the other common tools. This information may include your IP address (a number assigned to your computer when you use the Internet), the name of the web page from which you entered the Website, the type of browser or operating system you are using, the name of your Internet service provider, broad demographic data, your activity while using the Website (including access times, duration of visit on each page, new and repeat visit information, exit page information and general usage activity), and data relating to malfunctions or problems occurring when you use your computer with the Website.</p>
				<p>Discretionary Contact With Us &ndash; The Website provides information on how to contact us electronically through the Website and through email. Whenever you make such contact, you will be providing us with your name and contact information, such as email address, and any information you choose to include in the text of your message.</p>
				<p>Tracking &ndash; From the Website, we do not engage in the collection of personally identifiable information about your online activities over time and across third party websites or online services. Accordingly, we do not currently process or comply with any web browser's &quot;do not track&quot; signal or other mechanisms that provide consumers with the ability to exercise choice regarding the collection of personally identifiable information about your online activities over time and across third party websites. From time to time, we may allow third-party companies which provide advertisements or certain functionality to collect certain anonymous information when you visit our website. These companies may collect and use such information during your visits to this and other websites in order to provide advertisements on other sites about goods and services likely to be of greater interest to you. These companies will typically use a cookie or a third party web beacon to collect this information.</p>
				<p>Via the Applicable Software and the Services. When you download the Applicable Software and use the Services, you will provide to Anchor ID, and its affiliates will otherwise collect, types of personally identifiable information, including types not usually obtained through typical website usage or web-based applications. This information is used to identify and protect your accounts and communications, and includes technical, usage and other data and information, such as contact information (e.g. phone and email), authentication credentials (e.g. passwords, biometric information), location and GPS information, device information (such as device OS version and device hardware), unique device identifiers (including device IP address and mobile serial number), application software and peripherals. In addition, Anchor ID will collect data and information about your Third Party Transactions, including login times and usage activities log (collectively, &quot;Transaction Data&quot;); provided, however, that Anchor ID will not collect the content of transactions or communications between you and Applicable Third Parties that may be delivered through the your use of the Services.</p>
				<p>Tracking &ndash;Via the Applicable Software and the Services, we do not engage in the collection of personally identifiable information about your online activities across third party websites or online services. However, we do collect information (including Transaction Data) from your use of the Applicable Software and the Services across different Applicable Third Parties with whom you conduct Third Party Transaction.</p>

				<h3>HOW IS YOUR INFORMATION USED?</h3>
				<p>
				Information Collected through the Website. We collect, retain, and use the information we collect via the Website for legitimate business purposes only. This not only allows us to provide the Website and Mobile App as they exist today, but it also allows us to provide you with innovative features and services we develop in the future that use the information we receive about you in new ways. For example, we may use the information we receive about you:<br />
				<ul>
					<li>to establish you as a registered user and to provide the services offered by the Website;</li>
					<li>to help keep the Website safe and secure, and protect users' rights or property;</li>
					<li>to monitor your use of the Website,</li>
					<li>to measure or understand the effectiveness of the Website and, if applicable, the ads you and others see; and</li>
					<li>to correspond with you regarding the Website or matters relating to your use or potential use of the Website, or to inform you of developments in our company or with our services that we believe may be of interest to you. We use cookies and other automated and passive tools (such as log files) to gather broad demographic information for internal marketing and demographic studies; to help identify you as a Website user (especially when you return to the Website) and to track and personalize your use of the Website (and not other sites) so as to improve your user experience; to assess overall activity on the Website, including tracking interest in particular features of the Website; and for internal operations, including troubleshooting, diagnosing problems with servers, data analysis, testing, research and service improvement.</li>
				</ul><br>
				<p>
					Information Collected Through Download of the Applicable Software and Use of the Services. We collect, retain, and use the information we collect via your download and/or use of the Applicable Software and the Services (including Transactional Data) for legitimate business purposes only, including to facilitate the provision of the Services, software updates and product support, to improve our products, to verify compliance with the terms of the license for the Applicable Software, and/or for market, risk and trend analysis. Anchor ID may use and share this information, as long as it is shared in a form that does not identify you personally, in the course of providing services to Applicable Third Parties or otherwise.<br />
				</p>
				<p>
					Your trust is important to us, which is why we don't share any personal information we receive about you with others unless we have:
				</p>
				<ul>
					<li>received your permission; or</li>
					<li>given you notice, such as by telling you about it in this Privacy Policy; or</li>
					<li>removed your name or any other personally identifying information from it. We do not sell or rent your personally identifiable information to third parties for marketing purposes.</li>
				</ul><br>

				<p>We may share your personal information as follows:</p>
				<ul>
					<li>to protect and defend the rights, property, or safety of Anchor ID, our users, or others; and in connection with the enforcement of terms which may govern the Website, the Applicable Software or provision of the Services;</li>
					<li>to make available to appropriate Applicable Third Party with which you have a relationship, Transaction Data about transactions between you and the Applicable Third Party;</li>
					<li>with business firms contracted to provide specific services to us, such as a credit card processing company or SMS providers, in a manner consistent with this Privacy Policy. In situations such as this, the third party servicing firm will be contractually obligated to use your personal data only for the purpose for which our relationship with the firm exists, and the firm will not have the right to share your data with other organizations or contact you outside the bounds of their contract with us. However, we cannot guarantee compliance by such third party firm;</li>
					<li>when we believe it is appropriate to investigate, prevent, or take action regarding illegal or suspected illegal activities (such as for potential fraud or infringement), including disclosing personally identifiable information to Anchor ID customers or other third parties in connection with such activity. By visiting the Website or downloading and/or using the Applicable Software or the Services, you expressly authorize Anchor ID to make such disclosures.</li>
					<li>in response to lawful governmental requests or legal process (for example, a court order, search warrant or subpoena) and in other circumstances in which we have a good faith belief that a crime has been or is being committed by you or another user or that an emergency exists that poses a threat to the safety of you or another person; a</li>
				</ul><br>

				<h3>THIRD PARTY INFORMATION, SERVICES AND ADVERTISERS</h3>
				<p>In connection with the Services, information you have previously provided to Applicable Third Parties or as may be available in public repositories such as the telephone white pages, may be provided to Anchor ID by the Applicable Third Parties or other third party organizations. Information and data that is shared with Anchor ID by such third party providers is the property of the supplying entity. Anchor ID does not use any such information and data provided by third party providers except at the explicit instruction of our customers. The Website now or in the future may reference or provide links to third party services, websites, applications or products, including through third party advertisements. As noted under the caption &quot; Applicability of this Privacy Policy,&quot; this Privacy Policy does not apply to information about you collected by third party services, websites, applications or advertisements associated with, linked to or otherwise accessible from the Website or by Applicable Third Parties in connection with Third Party Transactions. Anchor ID does not control and is not responsible for such third party services, applications, websites or advertisements, or for the privacy policies or information practices of any such third parties or their services. You should review the privacy policies applicable to such third party services, applications, websites and advertisers.</p>

				
				<h3>MERGER OR ACQUISITION</h3>
				<p>If Anchor ID is merged with or acquired by another party, divests the Services to another party, or acquires another party, your personally identifiable information may be transferred to that party as a part of such merger, divestiture or acquisition. By use of this Website or the download and/or use of the Applicable Software or Services you expressly authorize such transfer.</p>

				<h3>COMMUNICATION YOU MAY RECEIVE FROM US/OPT-OUT</h3>
				<p>Anchor ID uses voluntarily provided information to send you announcements of new services, updates, promotional information and newsletters, as well as to provide the Services that you request and give you better customer service. You may opt out of receiving promotional materials or other communications from us by checking the appropriate box when you register. You may unsubscribe or &quot;opt out&quot; from these emails at any time by following the opt-out link provided in any email you received from us or by contacting us via the email address at the end of this Privacy Policy. Please note that even if you unsubscribe from promotional email messages, we may still contact you. For example, even if you have unsubscribed from our email messages, we will still send you emails confirming your preferences. Further, so long as you are using the Services, we will need to contact you with important information related to your Services account, including activation and deactivation notices, transactional information, and notices from Applicable Third Parties.</p>

				<h3>SECURITY</h3>
				<p>Anchor ID stores personally identifiable information in a secure manner and considers it to be part of the assets of its business. To prevent unauthorized access, maintain data accuracy and ensure the appropriate use of information, Anchor ID has put in place physical, electronic and administrative procedures to safeguard and secure the information it collects online. However, the Internet and data security are constantly evolving. As such, you should consider any communication or information you transmit to Anchor ID through unsecured means as non&ndash;confidential. You agree that Anchor ID will not be liable or responsible if information that belongs to you is intercepted and used by an unauthorized recipient.</p>

				<h3>MODIFICATIONS AND DELETIONS TO PERSONAL INFORMATION</h3>
				<p>We strive to maintain the accuracy of any personally identifiable information that may be collected from you, and will use our commercially reasonable efforts to respond promptly to update our database when you tell us the information in our database is not accurate. The mobile app provides you with access to your account profile and the ability to edit this information at the Account Management tab. Once you are no longer a registered Website user and cease to use the Applicable Software and Services, your account may be permanently deleted from the Anchor ID servers. Any such removed information may persist in backup copies for a reasonable period of time but will not be generally available. Certain information is needed to provide you with the Services, so we may delete this information only after you delete your account. Some of the things you do through the Services or on the Website are not stored in your account, but with business firms contracted to provide specific services to us, such as a credit card processing company or SMS providers. Such information may only be deleted in accordance with the privacy policy of such third parties. See above under the caption &quot;Our Sharing of Information&quot; in the section &quot;How Is Your Information Used?&quot;</p>

				<h3>INTERNATIONAL USERS -- APPLICABLE LAW AND EUROPEAN SAFE HARBOR POLICY</h3>
				<p>We collect, process, store, use, disclose and dispose of personal information that you submit to us in accordance with applicable United States law. Please note that the personal information you submit to Anchor ID will be transferred to Anchor ID operations centers, which may be located in the United States or elsewhere, to be processed by us in order to provide the Services to you or for such other purposes as set forth in this Privacy Policy. If you are not a resident of the United States, you acknowledge and agree that we may collect, process, store, use, disclose and dispose your personal information, as discussed in this Privacy Policy, outside your resident jurisdiction, and it is your responsibility for ensuring whether such actions and the sharing of information with Anchor ID through the Website, upon the download of the Applicable Software and/or use of the Services conforms to all local data protection laws applicable to you. In this regard, please be aware that United States law may offer different levels of protection for personal information than may be available in your country. Anchor ID complies with the U.S.-EU Safe Harbor Framework and the U.S.-Swiss Safe Harbor Framework as set forth by the U.S. Department of Commerce regarding the collection, use and retention of personal information from European Union member countries and Switzerland. Anchor ID has certified that it adheres to the Safe Harbor Privacy Principles of notice, choice, onward transfer, security, data integrity, access and enforcement. To learn more about the Safe Harbor program and to view Anchor ID's certification, please visit http://www.export.gov/safeharbor/.</p>

				<h3>CHILDREN</h3>
				<p>In compliance with the Children's Online Privacy Protection Act, 15 U.S.C. &sect;&sect; 6501-06 and 16 C.F.R. &sect;&sect; 312.1-312.12, Anchor ID will not knowingly collect or solicit personal information from anyone under the age of 13 or knowingly allow such persons to register. If you are under 13, please do not attempt to register for the Website or the Services, or send any information about yourself to us, including your name, address, mobile device number, or email address. By using the Website, downloading the Applicable Software or using the Services, you represent that you are not under 13 years of age.</p>

				<h3>UPDATES TO THIS POLICY</h3>
				<p>Anchor ID reserves the right to modify this Privacy Policy at any time, so please review it frequently. If we make any changes to this Privacy Policy, we will change the &quot;Last Updated&quot; date above. If we decide to change our Privacy Policy in regards to how we utilize any personally identifiable information, we will post a notice or link to those changes on our homepage. If we make other material changes to this Privacy Policy or if we change our email practices, we will notify you here, by email, or by means of a notice on our home page. If you use our Website after we post these changes, this indicates your acceptance of them.</p>

				<h3>Further Information</h3>
				<p>If you have questions about this Privacy Policy please contact Anchor ID at:<br /></p>
				<a href="mailto:privacy@AnchorID.com">privacy@AnchorID.com&#8232;</a>

				<p>Anchor ID, Inc.<br />
				One North Front St. Suite 103<br />
				Kingston, NY 12401</p>
			</div>

		</div>
	</div>
	<!-- Ends of Row First -->


</div>
<!-- About Page Ends Here -->
</div>
<?php include "includes/footer.php"; ?>
</body>
</html>